ConfigVersion: '2.0'
Misc:
  InGameOffenseNotifications: true
  LogOffensesInSeparateFile: true
  DisableInWorlds: []
  NotifyNearbyPlayers: false
  BreakMachinesInsteadOfDroppingItems: true
  ItemScanTimer: 10
Exploits:
  MineCart:
    MinecartBlockWhiteList: []
    PreventMinecartGlitch: true
    RemoveExistingGlitchedMinecarts: false
  PortalDupe:
    NetherWhiteListMode: true
    NotifyBlockedPortalAttempts: false
    EndWhiteList: []
    BlockNonPlayersInEndPortal: true
    EndWhiteListMode: true
    NetherWhiteList: []
    BlockNonPlayersInNetherPortal: true
  Other:
    PreventItemSwapLagExploit: true
    PreventRailDupe: true
    PreventHoppersToUnloadedChunks: true
    PreventZeroTickExploit: true
    PreventBedrockDestruction: true
    PreventNestedShulkers: true
    PreventInvalidPotions: true
    DisableChestsOnMobs: true
    PreventInvalidElytraFlight: true
  1_15_Exploits:
    Dupes:
      PreventTripwireDupe: true
  FishMod:
    MaxFishToNotifyStaffThenBlock: 5
    WarnPlayerThenKickInsteadOfNotify: false
    WatchForAutoFishMod: true
    MaxFishAllowedBeforeKick: 5
  OverStack:
    RemoveOverstackedItems: true
    StackWhiteListMode: true
    AllowStack:
    - POTION
    FixOverstackedItemInstead: false
    GroupStack: []
    PreventOverStackedItemInHoppers: true
    RemoveItemsOfType: []
  SignExploit:
    DestroyBadSignsOnChunkLoad: false
  1_14_Exploits:
    Traders:
      ZombieVillagerTransformChance: 100
      BlockVillagerTradeCheesing: true
      VillagerRestockTime: 10
  Nether:
    BlockPlayersAboveNether: true
    ExcludeNetherWorldFromHeightCheck: []
    NetherYLevel: 128
  Enchants:
    AllowBypass: false
    OnlyFunctionInWorlds: []
    RemoveUnbreakableFlag: false
    EnchantedItemWhitelist: []
    CustomEnchantOverride: []
    RemoveCustomAttributes: false
    FixIllegalEnchants: false
  BookExploit:
    BookAuthorWhitelist: []
    DisableBookWriting: false
    RemoveBooksNotMatchingCharset: true
    ValidCharset: US-ASCII
    PageCountThreshold: 5
    LimitNumberOfPages: 0
  Fishing:
    KickForAutoClickerFishing: true
  TNTDupe:
    PreventIndirectTNTPowerDupe: true
  RNGEnchant:
    PreventRNGEnchant: true
  3rdParty:
    BlockCMIShulkerStacking: true
  DropperDupe:
    BlockLoopedDroppers: false
  Teleport:
    PearlPhasing: true
UserRequested:
  Cobble:
    PreventCobbleGenerators: false
  ItemRemoval:
    ItemNamesToRemove: []
    BlockEnchantingInstead: false
    RemoveItemsMatchingName: false
    BlockRepairsInstead: false
    ItemLoresToRemove: []
    NameLoreStrictMatchMode: false
  Obscure:
    HopperCheck:
      IgnoreAllHopperChecks: false
    HackedShulker:
      CheckGroundForBadShulkerAtLogin: false
      DestroyInvalidShulkers: false
    BlockBadItemsFromCreativeTab: false
  Obsure:
    Misc:
      RemoveAllRenamedItems: false
  Mobs:
    PreventZombieItemPickup: false
  Misc:
    NotifyInsteadOfBlock: []
Exploit:
  Teleport:
    CorrectionNotify: false
  LagMachines:
    ArmorStand: true
    End Crystal: true
